In [1]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
import matplotlib.pyplot as plt
from interactions import *
import time

In [3]:
X = np.random.uniform(-1, 1, (10000, 2))
y = np.logical_xor(X[:, 0] >= 0, X[:, 1] >= 0)
model = DecisionTreeClassifier(max_depth=2)
model.fit(X, y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [3]:
test_data = np.random.uniform(-1, 1, (100, 2))
test_outcomes = model.predict(test_data)

In [9]:
print(fast_interactions(model, X, y, np.array([[-1, 1]]), np.array([1, 0]), continuous_y=False, class_id=1))
print(interactions_continuous(model, X, y, np.array([[-1, 1]]), np.array([1, 0]), continuous_y = False))

0.49324254616733726
[[0.         0.50675745]
 [1.         0.49324255]]


In [10]:
print(fast_interactions(model, X, y, np.array([[-1, 1]]), np.array([1, 1]), continuous_y=False, class_id=1))
print(interactions_continuous(model, X, y, np.array([[-1, 1]]), np.array([1, 1]), continuous_y = False))

0.5067393174648696
[[0.         0.49326068]
 [1.         0.50673932]]


In [11]:
print(fast_interactions(model, X, y, np.array([[-1, 1]]), np.array([0, 1]), continuous_y=False, class_id=1))
print(interactions_continuous(model, X, y, np.array([[-1, 1]]), np.array([0, 1]), continuous_y = False))

0.5033407572383074
[[0.         0.49665924]
 [1.         0.50334076]]


In [12]:
print(fast_interactions(model, X, y, np.array([[1, 1]]), np.array([1, 0]), continuous_y=False, class_id=1))
print(interactions_continuous(model, X, y, np.array([[1, 1]]), np.array([1, 0]), continuous_y = False))

0.5830618892508144
[[0.         0.41693811]
 [1.         0.58306189]]


In [11]:
for i in range(10):
    X = np.random.uniform(-1, 1, (10000, 2))
    y = np.logical_xor(X[:, 0] >= 0, X[:, 1] >= 0)
    model = DecisionTreeClassifier(max_depth=2)
    model.fit(X, y)
    print(fast_interactions(model, X, y, np.array([[1, 1]]), np.array([1, 0]), continuous_y=False, class_id=1))
    print(interactions_continuous(model, X, y, np.array([[1, 1]]), np.array([1, 0]), continuous_y = False))

0.5083719991930603
[[0.       0.491628]
 [1.       0.508372]]
never encountered relevant features
[[0.     0.5042]
 [1.     0.4958]]
0.5032176511146863
[[0.         0.49678235]
 [1.         0.50321765]]
0.4909759742499138
[[0.         0.50902403]
 [1.         0.49097597]]
0.49625074985003
[[0.         0.50374925]
 [1.         0.49625075]]
0.4721233689205219
[[0.         0.52787663]
 [1.         0.47212337]]
0.507500576967459
[[0.         0.49249942]
 [1.         0.50750058]]
0.49959887685519455
[[0.         0.50040112]
 [1.         0.49959888]]
0.5068631408962455
[[0.         0.49313686]
 [1.         0.50686314]]
0.5024945120734384
[[0.         0.49750549]
 [1.         0.50249451]]


In [17]:
t_start = time.clock()
for i in range(1000):
    X = np.random.uniform(-1, 1, (10000, 2))
    y = np.logical_xor(X[:, 0] >= 0, X[:, 1] >= 0)
    model = DecisionTreeClassifier(max_depth=2)
    model.fit(X, y)
    interactions_continuous(model, X, y, np.array([[1, 1]]), np.array([1, 0]), continuous_y = False)[1, 1]
t_end = time.clock()
print("time", t_end - t_start)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """Entry point for launching an IPython kernel.


time 16.514639


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:8: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  


In [18]:
t_start = time.clock()
for i in range(1000):
    X = np.random.uniform(-1, 1, (10000, 2))
    y = np.logical_xor(X[:, 0] >= 0, X[:, 1] >= 0)
    model = DecisionTreeClassifier(max_depth=2)
    model.fit(X, y)
    fast_interactions(model, X, y, np.array([[1, 1]]), np.array([1, 0]), continuous_y=False, class_id=1)
t_end = time.clock()
print("time", t_end - t_start)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """Entry point for launching an IPython kernel.


time 5.261737999999998


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:8: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  


In [7]:
X = np.random.uniform(-1, 1, (10000, 2))
y = np.logical_xor(X[:, 0] >= 0, X[:, 1] >= 0)
model = DecisionTreeClassifier(max_depth=2)
model.fit(X, y)
print(interactions_set(model, X, y, np.array([[1, 1]]), np.array([1, 0]), continuous_y=False, class_id=1))
print("------------the line is here----------")
print(interactions_set(model, X, y, np.array([[1, 1], [-.001, .1]]), np.array([1, 0]), continuous_y=False, class_id=1))

[0.5237879474399637]
------------the line is here----------
[0.5237879474399637, 0.4965995123829077]


In [2]:
X = np.random.uniform(0, 10, (10000, 2))
y = X[:, 0] * X[:, 1]
forest = RandomForestRegressor()
forest.fit(X, y)
test_set = np.random.uniform(0, 10, (10, 2))
print("test points", test_set)
print("expectation", test_set[:, 0] * 5)
test_scores = interactions_forest(forest, X, y, test_set, np.array([1, 0]))
print("test scores", test_scores)

/usr/local/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


test points [[8.47401684 6.55518662]
 [7.07010016 1.44635107]
 [6.61220738 2.12303715]
 [8.70642752 8.27636025]
 [4.42219211 5.27503056]
 [7.65342727 3.80202095]
 [8.75010106 7.51937792]
 [0.59761052 0.10281483]
 [3.4858356  7.73757619]
 [4.45843153 2.26243535]]
expectation [42.37008421 35.35050078 33.06103692 43.53213762 22.11096055 38.26713636
 43.7505053   2.98805261 17.42917801 22.29215767]
test scores [43.92165257 36.26292255 35.14090966 41.6452291  21.48583834 38.56715817
 43.56046278  3.10000575 17.74214393 21.77277043]
